
public class TestCases {
	public static void evalTest(){
		Visitor evaluator = new Evaluator();
		System.out.println("Evaluate:");
		String eval1 = "(1+2+3)";
		String eval2 = "((1-2)-3)";
		String eval3 = "(1+2)*3";
		String eval4 = "(4*5)/2";
		String eval5 = "x+1";
		String eval6 = "(5*x)+4-3*(4+5)";
		System.out.println("Equation: "+eval1);
		String postfix1 = TreeExp.IntoPost(eval1);
		Exp root1;
		root1 = TreeExp.makeExpTree(postfix1);
		System.out.println("Evaluated: "+root1.accept(evaluator));
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+eval2);
		String postfix2 = TreeExp.IntoPost(eval2);
		Exp root2;
		root2 = TreeExp.makeExpTree(postfix2);
		System.out.println("Evaluated: "+root2.accept(evaluator));
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+eval3);
		String postfix3 = TreeExp.IntoPost(eval3);
		Exp root3;
		root3 = TreeExp.makeExpTree(postfix3);
		System.out.println("Evaluated: "+root3.accept(evaluator));
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+eval4);
		String postfix4 = TreeExp.IntoPost(eval4);
		Exp root4;
		root4 = TreeExp.makeExpTree(postfix4);
		System.out.println("Evaluated: "+root4.accept(evaluator));
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+eval5);
		String postfix5 = TreeExp.IntoPost(eval5);
		Exp root5;
		root5 = TreeExp.makeExpTree(postfix5);
		System.out.println("Evaluated: "+root5.accept(evaluator));
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+eval6);
		String postfix6 = TreeExp.IntoPost(eval6);
		Exp root6;
		root6 = TreeExp.makeExpTree(postfix6);
		System.out.println("Evaluated: "+root6.accept(evaluator));
		System.out.println("                        ================                       ");
	}
	public static void diffTest() {
		System.out.println("Differentiate:");
		Visitor differentiater = new Diff();
		String diff1 = "x";
		String diff2 = "x*x*x";
		String diff3 = "x+2*x";
		String diff4 = "2*x+x*x+x+1";
		String diff5 = "(x*x)+(4*x)+1";
		String diff6 = "x*x*x*x*x*x*x +x+x+x+x+x+x";
		System.out.println("Equation: "+diff1);
		String postfix1 = TreeExp.IntoPost(diff1);
		Exp root1;
		root1 = TreeExp.makeExpTree(postfix1);
		root1 = (Exp) root1.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root1);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff2);
		String postfix2 = TreeExp.IntoPost(diff2);
		Exp root2;
		root2 = TreeExp.makeExpTree(postfix2);
		root2 = (Exp) root2.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root2);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff3);
		String postfix3 = TreeExp.IntoPost(diff3);
		Exp root3;
		root3 = TreeExp.makeExpTree(postfix3);
		root3 = (Exp) root3.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root3);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff4);
		String postfix4 = TreeExp.IntoPost(diff4);
		Exp root4;
		root4 = TreeExp.makeExpTree(postfix4);
		root4 = (Exp) root4.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root4);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff5);
		String postfix5 = TreeExp.IntoPost(diff5);
		Exp root5;
		root5 = TreeExp.makeExpTree(postfix5);
		root5 = (Exp) root5.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root5);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff6);
		String postfix6 = TreeExp.IntoPost(diff6);
		Exp root6;
		root6 = TreeExp.makeExpTree(postfix6);
		root6 = (Exp) root6.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root6);
		System.out.println();
		System.out.println("                        ================                       ");
	}
	public static void simplifyTest() {
		System.out.println("Simplify:");
		Visitor differentiater = new Diff();
		Visitor simplifier = new Simplify();
		String diff1 = "x";
		String diff2 = "x*x*x";
		String diff3 = "x+2*x";
		String diff4 = "2*x+x*x+x+1";
		String diff5 = "(x*x)+(4*x)+1";
		String diff6 = "x*x*x*x*x*x*x +x+x+x+x+x+x";
		System.out.println("Equation: "+diff1);
		String postfix1 = TreeExp.IntoPost(diff1);
		Exp root1;
		root1 = TreeExp.makeExpTree(postfix1);
		root1 = (Exp) root1.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root1);
		root1 = (Exp) root1.accept(simplifier);
		System.out.print("Simplified: ");
		TreeExp.inOrder(root1);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff2);
		String postfix2 = TreeExp.IntoPost(diff2);
		Exp root2;
		root2 = TreeExp.makeExpTree(postfix2);
		root2 = (Exp) root2.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root2);
		root2 = (Exp) root2.accept(simplifier);
		System.out.print("Simplified: ");
		TreeExp.inOrder(root2);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff3);
		String postfix3 = TreeExp.IntoPost(diff3);
		Exp root3;
		root3 = TreeExp.makeExpTree(postfix3);
		root3 = (Exp) root3.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root3);
		root3 = (Exp) root3.accept(simplifier);
		System.out.print("Simplified: ");
		TreeExp.inOrder(root3);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff4);
		String postfix4 = TreeExp.IntoPost(diff4);
		Exp root4;
		root4 = TreeExp.makeExpTree(postfix4);
		root4 = (Exp) root4.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root4);
		root4 = (Exp) root4.accept(simplifier);
		System.out.print("Simplified: ");
		TreeExp.inOrder(root4);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff5);
		String postfix5 = TreeExp.IntoPost(diff5);
		Exp root5;
		root5 = TreeExp.makeExpTree(postfix5);
		root5 = (Exp) root5.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root5);
		root5 = (Exp) root5.accept(simplifier);
		System.out.print("Simplified: ");
		TreeExp.inOrder(root5);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+diff6);
		String postfix6 = TreeExp.IntoPost(diff6);
		Exp root6;
		root6 = TreeExp.makeExpTree(postfix6);
		root6 = (Exp) root6.accept(differentiater);
		System.out.print("Differentaited: ");
		TreeExp.inOrder(root6);
		root6 = (Exp) root6.accept(simplifier);
		System.out.print("Simplified: ");
		TreeExp.inOrder(root6);
		System.out.println();
		System.out.println("                        ================                       ");
	}
	public static void mipsTest() {
		Visitor mipsGenerator = new MIPSAssemblyGeneration();
		System.out.println("MIPS Generate:");
		String mips1 = "1+2";
		String mips2 = "1-2";
		String mips3 = "1*2";
		String mips4 = "1/2";
		String mips5 = "x+1";
		String mips6 = "x*x*4+2";
		System.out.println("Equation: "+mips1);
		String postfix1 = TreeExp.IntoPost(mips1);
		Exp root1;
		root1 = TreeExp.makeExpTree(postfix1);
		root1 = (Exp) root1.accept(mipsGenerator);
		TreeExp.inOrder(root1);
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+mips2);
		String postfix2 = TreeExp.IntoPost(mips2);
		Exp root2;
		root2 = TreeExp.makeExpTree(postfix2);
		root2 = (Exp) root2.accept(mipsGenerator);
		TreeExp.inOrder(root2);
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+mips3);
		String postfix3 = TreeExp.IntoPost(mips3);
		Exp root3;
		root3 = TreeExp.makeExpTree(postfix3);
		root3 = (Exp) root3.accept(mipsGenerator);
		TreeExp.inOrder(root3);
		System.out.println();
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+mips4);
		String postfix4 = TreeExp.IntoPost(mips4);
		Exp root4;
		root4 = TreeExp.makeExpTree(postfix4);
		root4 = (Exp) root4.accept(mipsGenerator);
		TreeExp.inOrder(root4);
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+mips5);
		String postfix5 = TreeExp.IntoPost(mips5);
		Exp root5;
		root5 = TreeExp.makeExpTree(postfix5);
		root5 = (Exp) root5.accept(mipsGenerator);
		TreeExp.inOrder(root5);
		System.out.println("                        ================                       ");
		System.out.println("Equation: "+mips6);
		String postfix6 = TreeExp.IntoPost(mips6);
		Exp root6;
		root6 = TreeExp.makeExpTree(postfix6);
		root6 = (Exp) root6.accept(mipsGenerator);
		TreeExp.inOrder(root6);
	}
	public static void main(String[] args) {
		System.out.println("======================== FinalProject =========================");
		System.out.println("============== 5710546372 Pipatpol Tanavongchinda =============");
		System.out.println("Assume all test x equals 6.");
		evalTest();
		System.out.println("===============================================================");
		diffTest();
		System.out.println("===============================================================");
		simplifyTest();
		System.out.println("===============================================================");
		mipsTest();
		System.out.println("======================= End of program ========================");
	}
}
