
public class TestCases {
	public static void main(String[] args) {
		System.out.println("========================= Project 2 ===========================");
		System.out.println("============== 5710546372 Pipatpol Tanavongchinda =============");
		String equation1 = "( 8 + 9 * ( 4 + 5 * 7 + 6 ) ) + 3 * 5 + 4";
		System.out.println("Equation : "+equation1);
		System.out.println("Actual : "+((8+9*(4+5*7+6))+3*5+4));
		String postfix1 = TreeExp.IntoPost(equation1);
		System.out.println("IntoPost : "+postfix1);
		Exp root1;
		root1 = TreeExp.makeExpTree(postfix1);
		System.out.println("Result : "+root1.eval());
		System.out.print("Inorder : ");
		TreeExp.inOrder(root1);
		System.out.println("Print tree : ");
		TreeExp.printTree( root1, 0);
		System.out.println("=====================");
		String equation2 = "1 + 8 + 9 * 2";
		System.out.println("Equation : "+equation2);
		System.out.println("Actual : "+(1+8+9*2));
		String postfix2 = TreeExp.IntoPost(equation2);
		System.out.println("IntoPost : "+postfix2);
		Exp root2;
		root2 = TreeExp.makeExpTree(postfix2);
		System.out.println("Result : "+root2.eval());
		System.out.print("Inorder : ");
		TreeExp.inOrder(root2);
		System.out.println("Print tree : ");
		TreeExp.printTree( root2, 0);
		System.out.println("=====================");
		String equation3 = "7*5+(8+9*2)";
		System.out.println("Equation : "+equation3);
		System.out.println("Actual : "+(7*5+(8+9*2)));
		String postfix3 = TreeExp.IntoPost(equation3);
		System.out.println("IntoPost : "+postfix3);
		Exp root3;
		root3 = TreeExp.makeExpTree(postfix3);
		System.out.println("Result : "+root3.eval());
		System.out.print("Inorder : ");
		TreeExp.inOrder(root3);
		System.out.println("Print tree : ");
		TreeExp.printTree( root3, 0);
		System.out.println("=====================");
		String equation4 = "7*5+((8+9)*2)";
		System.out.println("Equation : "+equation4);
		System.out.println("Actual : "+(7*5+((8+9)*2)));
		String postfix4 = TreeExp.IntoPost(equation4);
		System.out.println("IntoPost : "+postfix4);
		Exp root4;
		root4 = TreeExp.makeExpTree(postfix4);
		System.out.println("Result : "+root4.eval());
		System.out.print("Inorder : ");
		TreeExp.inOrder(root4);
		System.out.println("Print tree : ");
		TreeExp.printTree( root4, 0);
		System.out.println("=====================");
		String equation5 = "((5+6*2*(4+8)))*(2+2)";
		System.out.println("Equation : "+equation5);
		System.out.println("Actual : "+(((5+6*2*(4+8)))*(2+2)));
		String postfix5 = TreeExp.IntoPost(equation5);
		System.out.println("IntoPost : "+postfix5);
		Exp root5;
		root5 = TreeExp.makeExpTree(postfix5);
		System.out.println("Result : "+root5.eval());
		System.out.print("Inorder : ");
		TreeExp.inOrder(root5);
		System.out.println("Print tree : ");
		TreeExp.printTree( root5, 0);
		System.out.println("=====================");
		
		System.out.println("========================= TreeCell test cases ===========================");
		System.out.println("Equation : "+equation1);
		System.out.println("Actual : "+((8+9*(4+5*7+6))+3*5+4));
		String postfix6 = TreeCell.IntoPost(equation1);
		System.out.println("IntoPost : "+postfix6);
		TreeCell root6= TreeCell.makeExpTree(postfix6);
		System.out.println("Result : "+TreeCell.eval(root6));
		System.out.print("Inorder : ");
		TreeCell.inOrder(root6);
		System.out.println("Print tree : ");
		TreeCell.printTree( root6, 0);
		System.out.println("=====================");
		System.out.println("Equation : "+equation2);
		System.out.println("Actual : "+(1+8+9*2));
		String postfix7 = TreeCell.IntoPost(equation2);
		System.out.println("IntoPost : "+postfix7);
		TreeCell root7 = TreeCell.makeExpTree(postfix7);
		System.out.println("Result : "+TreeCell.eval(root7));
		System.out.print("Inorder : ");
		TreeCell.inOrder(root7);
		System.out.println("Print tree : ");
		TreeCell.printTree( root7, 0);
		System.out.println("=====================");
		System.out.println("Equation : "+equation3);
		System.out.println("Actual : "+(7*5+(8+9*2)));
		String postfix8 = TreeCell.IntoPost(equation3);
		System.out.println("IntoPost : "+postfix8);
		TreeCell root8 = TreeCell.makeExpTree(postfix8);
		System.out.println("Result : "+TreeCell.eval(root8));
		System.out.print("Inorder : ");
		TreeCell.inOrder(root8);
		System.out.println("Print tree : ");
		TreeCell.printTree( root8, 0);
		System.out.println("=====================");
		System.out.println("Equation : "+equation4);
		System.out.println("Actual : "+(7*5+((8+9)*2)));
		String postfix9 = TreeCell.IntoPost(equation4);
		System.out.println("IntoPost : "+postfix9);
		TreeCell root9 = TreeCell.makeExpTree(postfix9);
		System.out.println("Result : "+TreeCell.eval(root9));
		System.out.print("Inorder : ");
		TreeCell.inOrder(root9);
		System.out.println("Print tree : ");
		TreeCell.printTree( root9, 0);
		System.out.println("=====================");
		System.out.println("Equation : "+equation5);
		System.out.println("Actual : "+(((5+6*2*(4+8)))*(2+2)));
		String postfix10 = TreeCell.IntoPost(equation5);
		System.out.println("IntoPost : "+postfix10);
		TreeCell root10 = TreeCell.makeExpTree(postfix10);
		System.out.println("Result : "+TreeCell.eval(root10));
		System.out.print("Inorder : ");
		TreeCell.inOrder(root10);
		System.out.println("Print tree : ");
		TreeCell.printTree( root10, 0);
		System.out.println("=====================");
		
		String equa = "1+3*(2*(3+5*4)+4)+7 ";
		System.out.println("Equation = "+equa);
		String postfix11 = TreeCell.IntoPost(equa);
		System.out.println("Postfix = "+postfix11);
		TreeCell root11 = TreeCell.makeExpTree(postfix11);
		System.out.println("Actual = "+(1+3*(2*(3+5*4)+4)+7 ));
		System.out.println("Result : "+TreeCell.eval(root11));
		TreeCell.printTree(root11, 0);
	}
}
